name: Demo Node.js CI/CD

# Trigger workflow on every push to main
on:
  push:
    branches: [ main ]

jobs:
  test-run:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run a test command (Jest)
      - name: Run tests
        run: npm test

      # 5. Simple deploy step (just runs the app)
      - name: Deploy (run app)
        run: node app.js

              # 5. Build Docker image (staging deployment)
      - name: Build Docker image
        run: docker build -t my-node-app .

      # 6. Run Docker container (simple staging/test environment)
      - name: Run Docker container
        run: docker run -d -p 3000:3000 my-node-app