name: Node.js CI/CD with Docker

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install dependencies (Node.js build)
      - name: Build Node.js app
        run: npm install

      # 4. Run Jest tests
      - name: Run tests
        run: npm test

  docker-deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      # 1. Checkout code again
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Build Docker image
      - name: Build Docker image
        run: |
          echo "Dockerfile must exist in root directory"
          docker build -t my-node-app:latest .

      # 3. Run Docker container
      - name: Run Docker container
        run: docker run -d -p 3000:3000 --name my-node-app my-node-app:latest