name: CI-CD-Pipleine

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v3

      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      
      - name: Build Node.js app
        run: npm install

      
      - name: Run tests
        run: npm test

  build-deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v3

      
      - name: Build Docker image
        run: docker build -t my-node-app:latest .

      
      - name: Run Docker container
        run: docker run -d -p 3000:3000 --name my-node-app my-node-app:latest
